In [1]:
import numpy as np
import pandas as pd
import json
from python_core.general import *
import pandas as pd

In [2]:
train_timestamp = json.load(open("Gowalla dataset/train_with_timestamps.json"))
test_timestamp = json.load(open("Gowalla dataset/test_with_timestamps.json"))

In [3]:
print(len(train_timestamp), len(test_timestamp))

675267 155132


In [4]:
for e in train_timestamp[:5]:
    info(e["history_events"])
    debug(e["target_event"])

INFO   [{'item_id': 1, 'raw_location_id': 608105, 'timestamp': '2010-05-22T02:49:04Z'}]
DEBUG  {'item_id': 2, 'raw_location_id': 8977, 'timestamp': '2010-05-22T17:50:55Z'}
INFO   [{'item_id': 1, 'raw_location_id': 608105, 'timestamp': '2010-05-22T02:49:04Z'}, {'item_id': 2, 'raw_location_id': 8977, 'timestamp': '2010-05-22T17:50:55Z'}]
DEBUG  {'item_id': 3, 'raw_location_id': 17269, 'timestamp': '2010-05-23T16:50:50Z'}
INFO   [{'item_id': 4, 'raw_location_id': 18417, 'timestamp': '2010-05-31T20:10:37Z'}]
DEBUG  {'item_id': 5, 'raw_location_id': 480992, 'timestamp': '2010-06-01T14:38:22Z'}
INFO   [{'item_id': 4, 'raw_location_id': 18417, 'timestamp': '2010-05-31T20:10:37Z'}, {'item_id': 5, 'raw_location_id': 480992, 'timestamp': '2010-06-01T14:38:22Z'}]
DEBUG  {'item_id': 6, 'raw_location_id': 15326, 'timestamp': '2010-06-02T00:28:29Z'}
INFO   [{'item_id': 4, 'raw_location_id': 18417, 'timestamp': '2010-05-31T20:10:37Z'}, {'item_id': 5, 'raw_location_id': 480992, 'timestamp': '2010-06-0

In [5]:
nyc_poi = np.load("data/NYC_POI.npy")
nyc = np.load("data/NYC.npy")

In [6]:
print(len(nyc_poi), len(nyc))

5135 147938


In [7]:
print(nyc_poi[:5])  # [loc_id, latitude, longitude]

[[  1.          40.73359624 -74.00313914]
 [  2.          40.75637696 -73.96765298]
 [  3.          40.73968518 -74.00601983]
 [  4.          40.71836265 -73.99081662]
 [  5.          40.7228417  -73.99411647]]


In [8]:
print(nyc[:10])  # [user_id, loc_id, timestamp]

[[     1    698  99366]
 [     1   3601   5743]
 [     1   3387 106770]
 [     1   1360  23332]
 [     1    571  98048]
 [     1    114 106894]
 [     1   1476 367574]
 [     1    698 170052]
 [     1   3788   7221]
 [     1    257  15046]]


In [9]:
print(nyc[0])

[    1   698 99366]


In [10]:
df = pd.DataFrame(nyc)

In [11]:
df.head()

,0,1,2
0,1,698,99366
1,1,3601,5743
2,1,3387,106770
3,1,1360,23332
4,1,571,98048


In [12]:
print(df[2].min())
print(df[2].max())

1
458435


In [30]:
import pickle

with open("Gowalla dataset/train.txt", "rb") as f:
    data = pickle.load(f)

In [31]:
print(data[0][:5])
print(data[1][:5])

[[1], [1, 2], [4], [4, 5], [4, 5, 6]]
[2, 3, 5, 6, 7]


In [15]:
with open("Gowalla dataset/all_train_seq.txt", "rb") as f:
    data = pickle.load(f)

In [16]:
print(data[0][:5])
print(data[1][:5])
print(data[2][:5])

[1, 2, 3]
[4, 5, 6, 7]
[8, 5, 9, 7, 10]


In [26]:
with open("Gowalla dataset/test.txt", "rb") as f:
    data = pickle.load(f)

In [28]:
print(data[0][:5])
print(data[1][:5])
print(data[2][:5])

[[2874], [2874, 445], [2874, 445, 1089], [2874, 445, 1089, 1139], [2874, 445, 1089, 1139, 729]]
[445, 1089, 1139, 729, 1305]


IndexError: tuple index out of range

In [17]:
from python_core.general import read_from_file

poi_metadata = read_from_file("Gowalla dataset/poi_metadata.json")

In [18]:
total_checkin = read_from_file("Gowalla dataset/loc-gowalla_totalCheckins.txt")

In [20]:
print(total_checkin[:10])

0	2010-10-


In [22]:
import pandas as pd
from io import StringIO

df = pd.read_csv(
    StringIO(total_checkin), 
    sep=r'\s+', 
    header=None, 
    names=['user_id', 'timestamp', 'latitude', 'longitude', 'location_id']
)

print(df)

         user_id             timestamp   latitude  longitude  location_id
0              0  2010-10-19T23:55:27Z  30.235909 -97.795140        22847
1              0  2010-10-18T22:17:43Z  30.269103 -97.749395       420315
2              0  2010-10-17T23:42:03Z  30.255731 -97.763386       316637
3              0  2010-10-17T19:26:05Z  30.263418 -97.757597        16516
4              0  2010-10-16T18:50:42Z  30.274292 -97.740523      5535878
...          ...                   ...        ...        ...          ...
6442887   196578  2010-06-11T13:32:26Z  51.742988  -0.488065       906885
6442888   196578  2010-06-11T13:26:45Z  51.746492  -0.490780       965121
6442889   196578  2010-06-11T13:26:34Z  51.741916  -0.496729      1174322
6442890   196585  2010-10-08T21:01:49Z  50.105516   8.571525       471724
6442891   196585  2010-10-07T17:39:18Z  50.027812   8.785098      4555073

[6442892 rows x 5 columns]
